In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.

np.__version__

'1.20.3'

In [8]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2, 3, 5))


In [9]:
#4. Print a.

print(a)

[[[0.2688707  0.28506441 0.75037681 0.76226697 0.79145649]
  [0.6947233  0.74068288 0.72085094 0.88894662 0.06661388]
  [0.70425808 0.70586791 0.23881631 0.4196628  0.73957737]]

 [[0.55079643 0.76600217 0.59390766 0.1743679  0.82455694]
  [0.31991492 0.53646866 0.37479128 0.14761459 0.81071941]
  [0.71778493 0.92072633 0.73596115 0.34331471 0.17703326]]]


In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

In [11]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size)
print(b.size)

30
30


In [14]:
#8. Are you able to add a and b? Why or why not? 

#Not since they have different numbers of Rows and Columns 

In [15]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [23]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a+c
print(a)

print(d)

[[[0.2688707  0.28506441 0.75037681 0.76226697 0.79145649]
  [0.6947233  0.74068288 0.72085094 0.88894662 0.06661388]
  [0.70425808 0.70586791 0.23881631 0.4196628  0.73957737]]

 [[0.55079643 0.76600217 0.59390766 0.1743679  0.82455694]
  [0.31991492 0.53646866 0.37479128 0.14761459 0.81071941]
  [0.71778493 0.92072633 0.73596115 0.34331471 0.17703326]]]
[[[1.2688707  1.28506441 1.75037681 1.76226697 1.79145649]
  [1.6947233  1.74068288 1.72085094 1.88894662 1.06661388]
  [1.70425808 1.70586791 1.23881631 1.4196628  1.73957737]]

 [[1.55079643 1.76600217 1.59390766 1.1743679  1.82455694]
  [1.31991492 1.53646866 1.37479128 1.14761459 1.81071941]
  [1.71778493 1.92072633 1.73596115 1.34331471 1.17703326]]]


In [24]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)
print(a)

#13. Does e equal to a? Why or why not? Yes they are equal since the first was multiplied by ones.

[[[0.2688707  0.28506441 0.75037681 0.76226697 0.79145649]
  [0.6947233  0.74068288 0.72085094 0.88894662 0.06661388]
  [0.70425808 0.70586791 0.23881631 0.4196628  0.73957737]]

 [[0.55079643 0.76600217 0.59390766 0.1743679  0.82455694]
  [0.31991492 0.53646866 0.37479128 0.14761459 0.81071941]
  [0.71778493 0.92072633 0.73596115 0.34331471 0.17703326]]]
[[[0.2688707  0.28506441 0.75037681 0.76226697 0.79145649]
  [0.6947233  0.74068288 0.72085094 0.88894662 0.06661388]
  [0.70425808 0.70586791 0.23881631 0.4196628  0.73957737]]

 [[0.55079643 0.76600217 0.59390766 0.1743679  0.82455694]
  [0.31991492 0.53646866 0.37479128 0.14761459 0.81071941]
  [0.71778493 0.92072633 0.73596115 0.34331471 0.17703326]]]


In [26]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()

d_min = d.min()

d_mean = d.mean()

print(f'El numero maximo es {d_max}')

print(f'El numero minimo es {d_min}')

print(f'La media es {d_mean}')

El numero maximo es 1.9207263263937677
El numero minimo es 1.066613879100287
La media es 1.5590665271777098


In [39]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2, 3, 5))
print(f)
             

[[[0.2688707  0.28506441 0.75037681 0.76226697 0.79145649]
  [0.6947233  0.74068288 0.72085094 0.88894662 0.06661388]
  [0.70425808 0.70586791 0.23881631 0.4196628  0.73957737]]

 [[0.55079643 0.76600217 0.59390766 0.1743679  0.82455694]
  [0.31991492 0.53646866 0.37479128 0.14761459 0.81071941]
  [0.71778493 0.92072633 0.73596115 0.34331471 0.17703326]]]


In [84]:
'''
#16. Populate the values in f. 

For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

d > d_min and d < d_mean = 25
d > d_mean and d < d_max = 75
d == d_mean = 50
d == d_min = 0
d == d_max = 100


'''

"\n#16. Populate the values in f. \n\nFor each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n\nd > d_min and d < d_mean = 25\nd > d_mean and d < d_max = 75\nd == d_mean = 50\nd == d_min = 0\nd == d_max = 100\n\n\n"

In [82]:
f = np.array([[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d])

In [83]:
f

array([[[ 25,  25,  75,  75,  75],
        [ 75,  75,  75,  75,   0],
        [ 75,  75,  25,  25,  75]],

       [[ 25,  75,  75,  25,  75],
        [ 25,  25,  25,  25,  75],
        [ 75, 100,  75,  25,  25]]])